version: "3.8"

volumes:
  data:

services:
  database:
      image: postgres:15
      volumes:
        - data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: 'Test1234'
        POSTGRES_USER: api
        POSTGRES_DB: zireael-db
      ports:
        - 5432:5432
